apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend  # This matches the label of the frontend pod
  ports:
    - protocol: TCP
      port: 80  # Expose externally on port 80
      targetPort: 80  # Map to the internal port 80 in the container
  type: LoadBalancer  