
apiVersion: v1
kind: Service
metadata:
  name: appointment-management-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '80'       # Service port (not targetPort)
    prometheus.io/path: '/metrics' # Metrics endpoint
spec:
  selector:
    app: appointment-management
  ports:
    - port: 80          # Service port
      targetPort: 5003  # Pod port (where /metrics is served)
  type: LoadBalancer
