apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: doctor-authentication-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: doctor-authentication-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
