
apiVersion: v1
kind: Service
metadata:
  name: doctor-authentication-service  # Update service name
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '80'       # Service port (not targetPort)
    prometheus.io/path: '/metrics'
spec:
  selector:
    app: doctor-authentication
  ports:
    - port: 80
      targetPort: 5001  # Pod port
  type: LoadBalancer