apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 80      # Internal port for Grafana
      targetPort: 3000  # Port that Grafana listens on inside the container
  type: LoadBalancer
