apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: location
  template:
    metadata:
      labels:
        app: location
    spec:
      containers:
        - name: location
          image: gcr.io/doctorhunt-application-456305/location-service:latest  # Correct image name

          env:
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "yourpassword"
            - name: DB_NAME
              value: "doctorhunt"
          ports:
            - containerPort: 5002
