apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 2Gi  # You can change the size as needed
  accessModes:
    - ReadWriteOnce  # This allows the volume to be mounted as read-write by a single node
  persistentVolumeReclaimPolicy: Retain  # Don't delete the volume when the PVC is deleted
  hostPath:
    path: /mnt/data/mysql  # This is the path on your host system where MySQL data will be stored
