apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-authentication-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-authentication
  template:
    metadata:
      labels:
        app: patient-authentication
    spec:
      containers:
        - name: patient-authentication
          image: gcr.io/doctorhunt-application-456305/patient-authentication:latest  # Correct image name

          env:
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "yourpassword"
            - name: DB_NAME
              value: "doctorhunt"
          ports:
            - containerPort: 5004
