apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: LoadBalancer  # Change to LoadBalancer for external access
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: prometheus
