apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: prometheus-service-account  # Use prometheus-specific service account here
    namespace: default
roleRef:
  kind: Role
  name: prometheus-role
  apiGroup: rbac.authorization.k8s.io
